# Numpy Demo
We'll go through some examples here.  There are also plenty of other guides online:
* [Numpy quickstart tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
* [Numpy for MATLAB users](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html) -- great reference if you already know MATLAB

To start working with any package, need to import it.

In [49]:
import numpy as np

# Motivation
Arrays are faster and more efficient than lists when working with numerical data.

## Pure Python

In [47]:
import random
import time

start = time.time()

n = 100

A = []
for i in range(n):
    row = []
    for j in range(n):
        row.append(random.random())
    A.append(row)
    
B = []
for i in range(n):
    row = []
    for j in range(n):
        row.append(random.random())
    B.append(row)
    
C = []
for i in range(n):
    row = []
    for j in range(n):
        sum = 0
        for k in range(n):
            sum += A[i][k] * B[k][j]
        row.append(sum)
    C.append(row)
    
stop = time.time()
print(stop - start)

0.47235560417175293


## Numpy

In [48]:
start = time.time()

n = 100

A = np.random.random((n, n))
B = np.random.random((n, n))
C = A @ B

stop = time.time()
print(stop - start)

0.0035321712493896484


# Creating Arrays
Numerous ways of creating arrays available.

* Creating arrays from a list

In [50]:
vals_list = [1, 3, 2, 8]
vals_array = np.array(vals_list)

print("vals_list: ", vals_list)
print("vals_array: ", vals_array)

vals_list:  [1, 3, 2, 8]
vals_array:  [1 3 2 8]


* Creating arrays using built-in functions
    * [np.arange()](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.arange.html)
    * [np.linspace()](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linspace.html)
    * How do we know how to call them?
        * See documentation
        * ipython help

In [15]:
print(np.arange(10))
print(np.arange(4,12))
print(np.arange(4,12,2))

[0 1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11]
[ 4  6  8 10]


In [16]:
print(np.linspace(0,1,11))
print(np.linspace(0,10,11))

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [56]:
print(np.zeros((5, 5,5))
#print(np.ones((4, 5))
#print(np.empty((6,5))

SyntaxError: unexpected EOF while parsing (<ipython-input-56-1c830b0c2586>, line 3)

# Data Types
As we saw, Python is dynamically typed.  Types are changed automatically as needed.  And, lists can hold anything.  A single list could hold strings and integers.

What about arrays?
Numpy arrays are statically typed.

So, what are the data types of the arrays we created above?  What are the available datatypes?  How do we specify what datatype we want? 

In [58]:
vals_list = [1,3,2,8]
vals_array = np.array(vals_list)
vals_arrayf = np.array(vals_list, dtype=np.float64)

print("vals_array: ", vals_array)
print("vals_arrayf: ", vals_arrayf)

print(type(vals_list))
print(type(vals_array))
print(type(vals_arrayf))

vals_array:  [1 3 2 8]
vals_arrayf:  [ 1.  3.  2.  8.]
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


The `dtype` argument is valid for most array-creation functions, including
`numpy.zeros`, `np.ones`, and `np.arange`.

In Python3, the `dtype` of an array that results from mathematical operations will
automatically adjust to whatever is sensible.

In [19]:
print('integers: ', vals_array)
print('more integers: ', vals_array * 3)
print('floats: ', vals_array / 3)

integers:  [1 3 2 8]
more integers:  [ 3  9  6 24]
floats:  [ 0.33333333  1.          0.66666667  2.66666667]


You can also copy an array and change the `dtype`.

In [20]:
arr = np.arange(10.0)
x = arr.astype(int)
print('arr: ', arr)
print('x: ', x)

arr:  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
x:  [0 1 2 3 4 5 6 7 8 9]


# Accessing Array Elements
Now that we actually have arrays, how do we get things from them?
Indexed from 0, bracket notation for accessing

In [21]:
print(vals_arrayf)
print(vals_arrayf[0])

[ 1.  3.  2.  8.]
1.0


Negative accessing is also allowed.

In [22]:
print(vals_arrayf[-1])

8.0


What if I want a section of an array?  Array slicing.

In [23]:
print(vals_arrayf[1:3])
print(vals_arrayf[1:2])

[ 3.  2.]
[ 3.]


In addition to a start and end, you can also choose a step for the slice.

In [24]:
print(vals_arrayf)
print(vals_arrayf[::2])  # odd indices
print(vals_arrayf[1::2])  # even indices
print(vals_arrayf[::-1])  # handy way to reverse an array

[ 1.  3.  2.  8.]
[ 1.  2.]
[ 3.  8.]
[ 8.  2.  3.  1.]


# Copies vs. Views (Accidentally changing your array)

You need to be careful with `numpy` arrays if you are
* trying to copy part of an array, or
* passing an array to a function

You might be in for a nasty surprise if you change an element.

In [59]:
simple = np.arange(5)
small = simple[:2]
print(simple)
print('')
print(small)
print('')

small[0] = 7
print(small)
print('')
print(simple)  # shouldn't have changed, right?

[0 1 2 3 4]

[0 1]

[7 1]

[7 1 2 3 4]


This happens because `small` is something called a "view" of
`simple`, rather than a copy. This helps `numpy` save memory and
speed up your program, but it can lead to tricky bugs if it
is not your intent. In general, it can be difficult to tell
whether something will be a view or a copy.

Functions also do not make copies of their input arrays.

In [26]:
def foo(x):  # notice that x is not returned
    x[0] = 100


foo(simple)
print(simple)

[100   1   2   3   4]


If you think you are accidentally changing your array elsewhere in your code,
you can copy it to be on the safe side. This will be slow your program down
and use more memory, but it can help debugging and save a lot of headaches.

In [27]:
print('before:')
print(simple)

my_copy = simple[:2].copy()
my_copy[1] = 10

foo(simple.copy())

print('after:')
print(simple)

before:
[100   1   2   3   4]
after:
[100   1   2   3   4]


# Multi-dimensional Arrays

*Note:* There is a `numpy.matrix` class, but you should avoid using it.
Use two-dimensional arrays instead.

How do we create multi-dimensional arrays?

In [28]:
# Creating from multi-dimensional lists
mat = np.array([[1,4,8],[3,2,9],[0,5,7]], float)
print(mat)
print('')

[[ 1.  4.  8.]
 [ 3.  2.  9.]
 [ 0.  5.  7.]]



In [60]:
# Creating special matrices
print(np.zeros((2,3), dtype=float))
print('')
print(np.zeros_like(mat))
print('')
# np.zeros_like creates a matrixsame shape, dimension, datatype as existing matrix
print(np.identity(3, dtype=float))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


How do we access multi-dimensional arrays?

In [30]:
print(mat)
print(mat[1,2])

[[ 1.  4.  8.]
 [ 3.  2.  9.]
 [ 0.  5.  7.]]
9.0


In [31]:
print(mat[0,0], mat[1,1], mat[2,2])

1.0 2.0 7.0


What about array slicing?

In [32]:
print(mat[1,:])

[ 3.  2.  9.]


In [33]:
print(mat[:,:2])

[[ 1.  4.]
 [ 3.  2.]
 [ 0.  5.]]


In [34]:
print(mat[:,1])

[ 4.  2.  5.]


What if we want an array of a different shape?
This can be a convenient way of initializing matrices.

In [61]:
arr = np.arange(8)
two_four = arr.reshape(2, 4)
four_two = arr.reshape(4, 2)
eight_none = arr.flatten()
print('array:')
print(arr)
print('')
print('2 x 4:')
print(two_four)
print('')
print('4 x 2:')
print(four_two)
print('')
print('back to array:')
print(eight_none)
print(eight_none.shape)

array:
[0 1 2 3 4 5 6 7]

2 x 4:
[[0 1 2 3]
 [4 5 6 7]]

4 x 2:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

back to array:
[0 1 2 3 4 5 6 7]
(8,)


# Array functions
We'll go through some array functions here.  There are plenty more available.  Best way to find the function you want is to search on Google for what you want and find the documentation for it (there is probably a function that does what you want to do).

Length of an array.
For multi-dimensional this is length of first axis

In [36]:
new_mat = mat[:,:2]
print(vals_arrayf)
print(new_mat)
print(len(vals_arrayf))
print(len(new_mat))

[ 1.  3.  2.  8.]
[[ 1.  4.]
 [ 3.  2.]
 [ 0.  5.]]
4
3


What about shape?

In [37]:
print(new_mat.shape) # not actually a function, but important

(3, 2)


What about sorting an array?
Two different methods, 
[np.sort()](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.sort.html) or 
[myarray.sort()](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.sort.html).
One is a numpy function (called as np.sort()) and returns a copy of the array in sorted order.
The other one is a function of the array and sorts the array in place.

**Important point:**
* Some functions operate in place, others return copies.
* How do you know which you are using?  Look at the documentation.

In [38]:
# Sort array
print(np.sort(vals_arrayf)) # returns a copy
print(vals_arrayf)
vals_arrayf.sort() # inplace
print(vals_arrayf)

[ 1.  2.  3.  8.]
[ 1.  3.  2.  8.]
[ 1.  2.  3.  8.]


In [39]:
# Checking if items are in an array
print(9 in mat)
print(9 in vals_arrayf)

True
False


Lots of elementwise operations happen automatically with arrays. These include:
* addition
* subtraction
* multiplication
* division
* comparisons

In [62]:
mat_2 = np.array([[1,3],[2,5]], float)
id_2 = np.identity(2, float)

print(mat_2)
print('')
print(id_2)
print('')
print('sum:')
print(mat_2 + id_2)
print('')
print('difference:')
print(mat_2 - id_2)
print('')
print('product:')
print(mat_2 * id_2)  # not matrix multiplication
print('')
print('quotient:')
print(id_2 / mat_2)
print('power:')
print(mat_2**3)  # not matrix exponentiation
print('')
print(mat_2 == id_2)
print(' ')
print(mat_2 > id_2)

[[ 1.  3.]
 [ 2.  5.]]

[[ 1.  0.]
 [ 0.  1.]]

sum:
[[ 2.  3.]
 [ 2.  6.]]

difference:
[[ 0.  3.]
 [ 2.  4.]]

product:
[[ 1.  0.]
 [ 0.  5.]]

quotient:
[[ 1.   0. ]
 [ 0.   0.2]]
power:
[[   1.   27.]
 [   8.  125.]]

[[ True False]
 [False False]]
 
[[False  True]
 [ True  True]]


In [41]:
# Other Functions
print(np.exp(id_2))
print(np.log2(vals_arrayf))
print(np.reciprocal(mat_2))

[[ 2.71828183  1.        ]
 [ 1.          2.71828183]]
[ 0.         1.         1.5849625  3.       ]
[[ 1.          0.33333333]
 [ 0.5         0.2       ]]


In [42]:
# Trig Functions
print(np.sin(mat_2))
print(np.tan(id_2))

[[ 0.84147098  0.14112001]
 [ 0.90929743 -0.95892427]]
[[ 1.55740772  0.        ]
 [ 0.          1.55740772]]


In [43]:
# Rounding
print(np.round(np.sin(mat_2), 2))

[[ 0.84  0.14]
 [ 0.91 -0.96]]


# Broadcasting (Element-wise operations on arrays of different shapes)

Note: `numpy` tries to make simple broadcasting fairly intuitive.
However, I *highly* reccomend [reading scipy's short article](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
on the topic if you are having trouble.

The simplest case is adding an array and a scalar.
What we want here should be fairly intuitive, and that is what `numpy` does.

In [63]:
bmat = np.arange(12).reshape(4, 3)
print(bmat)
print('')
print(3 + bmat)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


What about an array and a vector? What do we even mean by that?

In [45]:
vec3 = np.arange(3)
print(vec3)
print('')
print(bmat + vec3)

[0 1 2]

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


What if we want to add (or subtract, multiply, etc.) by row? We will need a vector of four elements for this to make sense.

In [46]:
vec4 = np.arange(4)
print(bmat + vec4)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

It turns out that `numpy` is comparing the 4 with the 3 and doesn't like it.
For an explanation of why, please read the scipy artice above (it really is short).

The gist is more or less that `numpy` prepends 1s to the size of your vector when broadcasting,
and each dimension of the two arrays either needs to be the same number or have one of the
numbers be a 1 for the operation to be valid.

In our case, one operand is (4, 3), and the other becomes (1, 4), so the 3 and the 4
in the last spot produce a `ValueError`.

So, how can we get around this?

In [64]:
print(bmat + vec4[:, np.newaxis])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


The `np.newaxis` in the second dimension forces `numpy` to put the 1 in that spot,
giving us a shape of (4, 1).  The (4, 1) shape lines up with the (4, 3) shape of
our matrix, so we are good to go.

Note that `np.newaxis` is not a command and does not have parentheses at the end.

# Reduction Operations

There are other operations that do not return an array of the same shape as the input.
For example, you can find out the minimum or maximum value in the entire array,
or the sum of all entries.

In [65]:
print(bmat)
print(bmat.min())
print(bmat.max())
print(bmat.sum())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
11
66


What if I want the smallest number in every row?
All of these reduction operations take an optional `axis` argument that allows
us to target a particular dimension of the array.

In [66]:
print('row minimum:')
print(bmat.min(axis=1))
print('column minimum:')
print(bmat.min(axis=0))

row minimum:
[0 3 6 9]
column minimum:
[0 1 2]


Notice that when we pass an `axis` argument, we lose that dimension of our
array, but the shape is otherwise unchanged. So, a (4, 3) array becomes
a (3,) array if we pass `axis=0`, and it becomes a (4,) array if we
pass `axis=1`.

# Treating Arrays as Matrices and Vectors

If `*` is elementwise multiplication, how do we do matrix multiplication?

In [67]:
# Matrix Multiplication and Dot Product
print(np.dot(mat_2, id_2))
print('')
print(mat_2 @ id_2)
print('')
print(np.dot(vals_arrayf, np.array([0,2,6,1])))

[[ 1.  3.]
 [ 2.  5.]]

[[ 1.  3.]
 [ 2.  5.]]

26.0


In [68]:
# Matrix transpose
print(np.transpose(mat_2))
print(mat_2.T)

[[ 1.  2.]
 [ 3.  5.]]
[[ 1.  2.]
 [ 3.  5.]]


# Random Numbers

You will often be asked to generate random numbers.
`numpy` can generate numbers from a variety of distributions,
and it can generate lots of them at once and put them in a convenient shape.

The [np.random](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html) documentation gives a helpful overview.

Some of the more common functions you might use are
[np.random.rand](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.rand.html#numpy.random.rand) (uniform),
[np.random.randn](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.randn.html#numpy.random.randn) (normal),
and [np.random.randint](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.randint.html#numpy.random.randint) (integers).
All of these routines give you the option of generating an array of a specified shape.

In [69]:
uniform_nums = np.random.rand(10)
print(uniform_nums)
print('')
normal_nums = np.random.randn(3, 5)
print(normal_nums)
print('')
integers = np.random.randint(0, 10, (4, 2))
print(integers)
print('')

[ 0.87946941  0.90905692  0.43295679  0.64558369  0.63274824  0.7941695
  0.53740849  0.22960303  0.03067978  0.37050331]

[[-0.54507313 -1.31707226 -1.18475274  0.37982798 -0.58013378]
 [-0.07545819  0.25449368 -0.67810699  0.90105193  0.10828502]
 [-0.03520025  0.161676   -1.08593744 -1.3979194   0.01533665]]

[[1 0]
 [6 2]
 [2 7]
 [3 8]]



# What Else is There in Numpy
This tutorial didn't really get in to any of the functions in 
[numpy.linalg](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html).
We'll see a lot of those functions in class.